services:
  localstack:
    image: localstack/localstack:latest
    container_name: naws-localstack
    ports:
      - "4566:4566" # LocalStack Gateway
      - "4510-4559:4510-4559" # External services port range
    environment:
      # Core LocalStack settings
      - SERVICES=s3,sqs,logs,batch,events,scheduler,sts,iam
      # - DEBUG=1
      # - PERSISTENCE=1
      # - DOCKER_HOST=unix:///var/run/docker.sock

      # AWS configuration
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

      # LocalStack Pro features (optional - remove if not using Pro)
      # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}

      # Hostname configuration
      # - HOSTNAME=localhost
      # - HOSTNAME_EXTERNAL=localhost
    volumes:
      - "./.localstack:/etc/localstack/init/ready.d"
    networks:
      - naws-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  localstack-data:

networks:
  naws-network:
    driver: bridge
